name: Cypress Tests
on:
  push:
    branches: [master]
    
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    env:
      working-directory: ./cypress   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ${{env.working-directory}}
          command: microapptests/ci-scripts/cypress_calender.sh
          run: cp ../ci-scripts/cypress_calender.sh


