name: Cypress Tests
on:
  push:
    branches: [master]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    env:
      working-directory: ./cypress   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: npm install

      - name: run cypress
        working-directory: ${{env.working-directory}}
        run: |
          npx  $(npm bin)/cypress run --config-file regressionconfig.json
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}