name: Cypress Tests

on:
  push:
    branches: [master]
    
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          working-directory: ./cypress   

      - name: Install dependencies
        run: npm install

      - name: run cypress
        run: |
          cp ../ci-scripts/cypress_calender.sh  cypress_calender.sh 
          sh cypress_calender.sh

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}


