name: Deploy static content and list artifact

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  prepare-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Clear old deployment
        run: |
          rm -rf deployment

      - name: Create deployment directory
        run: |
          mkdir -p deployment/github-pages
          cp -r zr/ deployment/github-pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: 'deployment'
          retention-days: 5

  list-artifact-contents:
    runs-on: ubuntu-latest
    needs: prepare-deployment
    steps:
      - name: Download artifact
        uses: actions/download-pages-artifact@v2
        with:
          name: github-pages

      - name: List contents of artifact
        run: |
          echo "Listing contents of the artifact:"
          ls -R
