name: Deploy Jekyll Site Version 1.0

on:
  push:
    branches:
      - master  # Or your branch for version 1.0

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Build site
        run: JEKYLL_ENV=production bundle exec jekyll build --config v1.0/_config-v1.0.yml -d v1.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./v1.0
      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.TOKEN }}
          
