name: Deploy Karate Reports

on:
  push:
    branches:
      - master  # Or your branch for deploying reports

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          
      - name: Install dependencies
        run: bundle install
        
      - name: Build site
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")  # Generate timestamp with format: YYYYMMDDHHMMSS
          echo "Current Timestamp: ${TIMESTAMP}"  # Print the timestamp to the console
          mkdir -p reports/${TIMESTAMP}
          cp index1.html reports/${TIMESTAMP}/index1.html


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}  # Use 'github_token' for authentication
          publish_branch: gh-pages  # Branch to which reports will be deployed
          publish_dir: ./reports     # Directory to publish
