name: Deploy Karate Reports

on:
  push:
    branches:
      - master  # Or any branch you want to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to get access to the code and the .git directory
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set git configuration
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Generate report directory structure
      - name: Create report directory structure
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")  # Generate timestamp with format: YYYYMMDDHHMMSS
          ENVIRONMENT="blitz"  # Example environment; can be dynamic based on input or context
          REPORTS_DIR="reports/${ENVIRONMENT}/${TIMESTAMP}"
          mkdir -p "${REPORTS_DIR}"  # Ensure the directory exists
          echo "Sample report content" > "${REPORTS_DIR}/report.html"  # Sample report

      # Commit and push to the gh-pages branch
      - name: Push to GitHub Pages
        run: |
          git fetch origin gh-pages  # Fetch the latest gh-pages branch
          git checkout gh-pages || git checkout --orphan gh-pages  # Checkout gh-pages branch or create it if it doesn't exist
          git reset --hard  # Clear current contents
          git add reports/  # Add only the reports directory to the commit
          git commit -m "Deploy reports for $ENVIRONMENT at $TIMESTAMP"
          git push origin gh-pages  # Push to the gh-pages branch
