name: Run Cypress Cloud E2E Tests

on:
  schedule:
    - cron: '30 21,23 * * 0,1,2,3,4'
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Select Environment'
        type: choice
        options:
          - blitzv2
          - stagev2
          - sandboxv2
          - production
        default: blitzv2
        required: true
      test_type:
        description: 'Select Test Type'
        type: choice
        options:
          - Smoke
          - Regression
          - Sanity
        default: Regression
        required: true
      cloud_record:
        description: 'Cypress cloud record'
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'
      test_options:
        description: 'Provide test options in the JSON string'
        type: string
        default: '{"parent_account_admin":true,"account_admin":true,"workspace_admin":true,"vault_creator":true,"vault_owner":true,"function_admin":true,"connection_manager":true,"schema_validation":true}'
      browser:
        description: 'Select Browser'
        type: choice
        options:
          - chrome
          - firefox
          - chromium
          - edge
        default: chrome

jobs:
  calculate-containers-count:
    runs-on: ubuntu-latest
    outputs:
      default_containers: ${{ steps.set-default.outputs.default_containers }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Set default containers
        id: set-default
        run: |
          cloud_record="${{ github.event.inputs.cloud_record || 'true' }}"
          environment_name="${{ github.event.inputs.environment_name }}"

          if [[ "$cloud_record" == "true" && ("$environment_name" == "production" || "$environment_name" == "prod") ]]; then
            regions=$(cat cypress/sanity-test-config.json)
            echo "Regions: $regions"
            default_containers=$(echo "$regions" | jq -c '[.regions[] | {workspace_id: .workspace_id, vault_id: .vault_id, display_name: .display_name, data_plane_url: .data_plane_url, workspace_url: .workspace_url, run_create_function_tests: .run_create_function_tests}]')
            echo "default_containers=$default_containers" >> $GITHUB_ENV

          elif [[ "$cloud_record" == "true" || "${{ github.event_name }}" == "schedule" ]]; then
            echo "default_containers=[1, 2, 3, 4, 5]" >> $GITHUB_ENV
          else
            echo "default_containers=[1]" >> $GITHUB_ENV

          # Debugging output
          echo "Final Default Containers: $default_containers"

  dryrun-matrix:
    needs: calculate-containers-count
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: ${{ fromJson(needs.calculate-containers-count.outputs.default_containers) }}
    steps:
      - name: Debug Output
        run: |
          echo "Default containers JSON: ${{ needs.calculate-containers-count.outputs.default_containers }}"
          echo "Parsed JSON:"
          echo "${{ needs.calculate-containers-count.outputs.default_containers }}" | jq .
