name: blitz-deploy

on:
  push:
    branches: [master]
jobs:
  check-codebase-changes:
    name: Check for the changes in codebase
    runs-on: ubuntu-latest
    outputs:
      core_folder_changes: ${{ steps.check_core_folder_changes.outputs.core_folder_changes }}
      changes_in_app: ${{ steps.check_core_folder_changes.outputs.changes_in_app }}
      changes_in_beffe: ${{ steps.check_core_folder_changes.outputs.changes_in_beffe }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history in case if the merge made with out squash

      - name: List changed files
        run: |
          git fetch origin main
          git diff --name-only origin/main...HEAD > changed_files.txt
          cat changed_files.txt
      - name: Check for core folder changes
        id: check_core_folder_changes
        run: |
          if grep -qE '^(?!app_test/|cypress/)' changed_files.txt; then
            echo "core_folder_changes=true" >> $GITHUB_OUTPUT
          else
            echo "core_folder_changes=false" >> $GITHUB_OUTPUT
          fi
          if grep -q '^app/' changed_files.txt; then
             echo "changes_in_app=true" >> $GITHUB_OUTPUT
          else
             echo "changes_in_app=false" >> $GITHUB_OUTPUT
          fi
          if grep -qE '^cypress/|^vault-beffe/' changed_files.txt; then
             echo "changes_in_beffe=true" >> $GITHUB_OUTPUT
          else
             echo "changes_in_beffe=false" >> $GITHUB_OUTPUT
          fi
  build-app:
    runs-on: ubuntu-latest
    needs: [make-tag,check-codebase-changes]
    if: ${{ needs.check-codebase-changes.outputs.core_folder_changes == 'true' }}
    run: echo "build-app step ran"
    
  build-data-beffe:
    runs-on: ubuntu-latest
    needs: [make-tag,check-codebase-changes]
    if: ${{ needs.check-codebase-changes.outputs.core_folder_changes == 'true' }}
    run: echo "build-beffe step ran"
    
  build-beffe-tests:
    runs-on: ubuntu-latest
    needs: [make-tag,check-codebase-changes]
    if: ${{ needs.check-codebase-changes.outputs.core_folder_changes == 'true' }}
    run: echo "build-beffe-tests step ran"
    
  run-cypress-karate-smoke-tests:
    needs: [make-tag, build-app, build-beffe, build-data-beffe,check-codebase-changes]
    if: ${{ needs.check-codebase-changes.outputs.changes_in_app == 'true' || needs.check-codebase-changes.outputs.changes_in_beffe == 'true' }}
    run: echo "run-cypress-karate-smoke-tests running"
    steps:
      - name: Check Cypress test results
        id: check_cypress_results
        if: ${{ (failure() || success()) && needs.check-codebase-changes.outputs.changes_in_app == 'true' }}
        run: echo "CYPRESS_TESTS_PASSED=true" >> $GITHUB_ENV
        
      - name: Upload Cypress Test Reports as Artifacts #only uploads if failures exists
        if: ${{ (failure() || success()) && needs.check-codebase-changes.outputs.changes_in_app == 'true' && env.CYPRESS_TESTS_PASSED == 'false' }}
        run: echo "ran"

  make-tag: 
    runs-on: ubuntu-latest
    needs: check-codebase-changes
    run: echo "make tag run"
