regions:
  - data_plane_url: https://re496gagin4x.vault.amazonewr323frer.com
    display_name: xpv.Oregon
    run_create_function_tests: false
    functions_deployed: false
    vault_id: e36f01a644fe44c7bdba23931007a43d
    workspace_id: a7885e3f4cd14e3ab4fad3c86896aea1
  - data_plane_url: https://cf1724dcabb5.vault.amazonewr323frer.com
    display_name: prod6.Bahrain
    run_create_function_tests: false
    functions_deployed: false
    vault_id: k9e893f9a8074eeb8ead9a9e40d45a0f
    workspace_id: a074bde15a484954a74f5ac6d54cf57d
