name: Run Karate Tests and Notify Slack

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Select Environment'
        type: choice
        options:
          - blitzv2
          - stagev2
          - sandboxv2
        default: blitzv2
        required: true
      test_type:
        description: 'Select Test Type'
        type: choice
        options:
          - regression
          - smoke
        default: regression
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "DEPLOYMENT_URL=https://example.com/deployment-url" >> $GITHUB_ENV
          echo "TEST_TYPE=${{ github.event.inputs.test_type }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment_name }}" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV

      - name: Run Karate tests
        run: echo "Simulating Karate test run... (No actual tests in this example)"

      - name: Send Slack Notification
        run: |
          mvn compile exec:java -Dexec.mainClass=com.intuit.karate.junit5.SlackNotification \
          -Dexec.args="Deployment URL: ${{ env.DEPLOYMENT_URL }} Test Type: ${{ env.TEST_TYPE }} Environment: ${{ env.ENVIRONMENT }} Timestamp: ${{ env.TIMESTAMP }}"

