name: Deploy Version to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger deployment from the master branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine version branch
        id: version
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)  # Generate a unique timestamp version
          echo "VERSION=version-${VERSION}" >> $GITHUB_ENV
          echo "Branch for version: $VERSION"

      - name: Set up deployment directory
        run: |
          mkdir -p deployment
          cp index1.html deployment/index.html  # Adjust as needed

      - name: Create deployment branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b $VERSION
          git add deployment
          git commit -m "Deploy version ${VERSION}"
          git push origin $VERSION

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
