name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      release_env:
        description: 'Environment to run the tests' 
        required: true
        default: 'sandbox'
      dryRun:
        description: 'Set to true to skip actual execution'
        required: true
        default: 'false'
      trigger_failure:
        type: choice
        options:
           - true
           - false

env:
  release_env: ${{ inputs.release_env }}
  dry-run: ${{ inputs.dryRun }}

jobs:
  test-logic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set Environment Name
        if: ${{ (env.release_env == 'sandbox' || env.release_env == 'prod') && env.dry-run == 'false' }}
        run: |
          echo "envname=$([[ ${{ env.release_env }} == 'sandbox' ]] && echo 'sandboxv2' || echo 'production')" >> $GITHUB_ENV
          echo "Environment name set to ${{ env.envname }}"

      - name: Trigger sanity tests in cypress cloud
        if: ${{ (env.release_env == 'sandbox' || env.release_env == 'prod') && env.dry-run == 'false' }}
        run: |
          echo "TRIGGER_FAILURE=${{ github.event.inputs.trigger_failure }}" >> $GITHUB_ENV
          echo "Would trigger sanity tests in cypress cloud"
          echo "Using environment: ${{ env.envname }}"
          echo "Using environment: ${{ github.event.inputs.trigger_failure }}"

      - name: Monitor sanity tests of cypress
        if: ${{ (env.release_env == 'sandbox' || env.release_env == 'prod') && env.dry-run == 'false' && github.event.inputs.trigger_failure == 'true'}}
        id: sanity-tests-cypress-status
        run: |
          echo "Would monitor sanity tests of cypress"
          echo "Checking status of workflow for repo: ${{ env.studio-ui-repo }}"
          exit 1
          
      - name: Trigger cypress regression tests 
        if: ${{ env.release_env == 'sandbox' && env.dry-run == 'false' }}
        run: |
          echo "Would trigger regression tests in cypress"
          echo "Environment name: sandboxv2"


      - name: Validate status of cypress github workflows
        if: ${{ env.release_env == 'sandbox' && env.dry-run == 'false' }}
        run: |
          echo "Would validate status of cypress GitHub workflows"
          echo "Repo: ${{ env.studio-ui-repo }}"
