name: Deploy HTML files to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment and Timestamp
        run: |
          ENV_NAME= "dev"
          TIMESTAMP=$(date +%s)
          DEPLOY_PATH="${ENV_NAME}/reports-${TIMESTAMP}"
          echo "DEPLOY_PATH=$DEPLOY_PATH" >> $GITHUB_ENV

      - name: Prepare HTML files for deployment
        run: |
          mkdir -p $DEPLOY_PATH
          cp index.html $DEPLOY_PATH/
          cp index2.html $DEPLOY_PATH/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
          folder: $DEPLOY_PATH
