name: Deploy Multiple Versions to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment from the master branch
  workflow_dispatch:  # Allow manual trigger of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: # Define the environment dynamically
      name: ${{ inputs.environment || 'production' }}  # Default to 'production' if not provided

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up deployment directory
        run: |
          # Define the version based on timestamp or a fixed version name
          VERSION=$(date +%Y%m%d%H%M%S)
          mkdir -p deployment/${VERSION}
          cp index1.html deployment/${VERSION}/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: 'deployment'
          retention-days: 30  # Adjust the retention period as needed

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
